version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # Monday at 9am JST
      timezone: "Asia/Tokyo"
      time: "09:00"
    groups:
      dependencies:
        patterns:
          - "*"
