[tools]
"aqua:suzuki-shunsuke/tfcmt" = "latest"
sops = "3.10.2"
terraform = "1.12.2"
tflint = "0.58.0"
vault = "latest"
vlt = "latest"

[env]
_.file = ".env.yaml"

[settings.sops]
age_key_file = "~/.config/mise/age.txt"
