name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"

jobs:
  lint:
    name: Terraform Lint
    runs-on: rx2530
    timeout-minutes: 10
    defaults:
      run:
        working-directory: terraform
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Mise dependencies
        run: mise install

      - name: Extract backend.tfbackend
        run: |
          echo "${{ secrets.TERRAFORM_BACKEND_CONFIGURATION }}" | base64 -d  \
            > backend.tfbackend

      - name: Terraform init
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform fmt
        run: terraform fmt -check

      - name: TFLint
        run: tflint

  apply:
    name: Terraform Apply
    needs:
      - lint
    runs-on: rx2530
    timeout-minutes: 10
    defaults:
      run:
        working-directory: terraform
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Mise dependencies
        run: mise install

      - name: Extract backend.tfbackend
        run: |
          echo ${{ secrets.TERRAFORM_BACKEND_CONFIGURATION }} | base64 -d  \
            > backend.tfbackend

      - name: Terraform init
        id: init
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform apply
        id: apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt apply -var "target:${{ matrix.target }}" -- terraform apply --auto-approve
