name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

jobs:
  lint:
    name: Terraform Lint
    runs-on: rx2530
    timeout-minutes: 10
    defaults:
      run:
        working-directory: terraform
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
        with:
          cache: false

      - name: Extract backend.tfbackend
        run: |
          echo "${{ secrets.TERRAFORM_BACKEND_CONFIGURATION }}" | base64 -d  \
            > backend.tfbackend

      - name: Terraform init
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform fmt
        run: terraform fmt -check

      - name: TFLint
        run: tflint

      - name: Terraform apply format
        if: failure()
        run: terraform fmt

      # 変更が発生した場合は プルリクエストを作成
      # https://github.com/peter-evans/create-pull-request
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: failure()
        with:
          delete-branch: true
          commit-message: "Auto format"
          committer: "GitHub Actions <noreply@github.com>"
          base: ${{ github.head_ref }}
          branch: "auto-format/${{ github.head_ref }}"
          title: "Auto Format: ${{ github.head_ref }}"
          body: "Auto Format: ${{ github.head_ref }} by GitHub Actions\nby: ${{github.actor}}"
          labels: "Auto Format"
          reviewers: ${{ github.actor }}

  plan:
    name: Terraform Plan
    needs:
      - lint
    runs-on: rx2530
    timeout-minutes: 10
    defaults:
      run:
        working-directory: terraform
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
        with:
          cache: false

      - name: Extract SOPS secrets
        run: |
          mkdir -p ~/.config/mise
          echo "${{ secrets.SOPS_FILE }}" > ~/.config/mise/flutterkaigi.txt

      - name: Extract backend.tfbackend
        run: |
          echo "${{ secrets.TERRAFORM_BACKEND_CONFIGURATION }}" | base64 -d  \
            > backend.tfbackend

      - name: Check directory is not empty
        run: |
          if [ -z "$(ls -A)" ]; then
            echo "Directory is empty! Please add a Terraform file to the directory."
            exit 1
          fi

      - name: Terraform init
        id: init
        run: terraform init -backend-config=backend.tfbackend

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -patch -var "target:${{ matrix.target }}" -- terraform plan -input=false
